name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry
      - run: poetry install
      - run: poetry run mkdocs build -v
      - name: Deploy Docs
        uses: ./.github/composites/docs-publish
        with:
          aws-role: ${{ secrets.DOC_PUBLISH_ROLE }}
          bucket-url: s3://docs-stage.cloudcustodian.io/docs/${{github.event.number}}
          docs-dir: site
